package cn.cs.fileManager.dao.mapper;

import cn.cs.fileManager.dao.model.FmFolder;
import cn.cs.fileManager.dao.model.FmFolderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FmFolderMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_folder
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	long countByExample(FmFolderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_folder
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	int deleteByExample(FmFolderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_folder
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	int insert(FmFolder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_folder
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	int insertSelective(FmFolder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_folder
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	List<FmFolder> selectByExample(FmFolderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_folder
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	int updateByExampleSelective(@Param("record") FmFolder record, @Param("example") FmFolderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_folder
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	int updateByExample(@Param("record") FmFolder record, @Param("example") FmFolderExample example);
}