package cn.cs.fileManager.dao.mapper;

import cn.cs.fileManager.dao.model.FmRole;
import cn.cs.fileManager.dao.model.FmRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FmRoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_role
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	long countByExample(FmRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_role
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	int deleteByExample(FmRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_role
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	int insert(FmRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_role
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	int insertSelective(FmRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_role
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	List<FmRole> selectByExample(FmRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_role
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	int updateByExampleSelective(@Param("record") FmRole record, @Param("example") FmRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_role
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	int updateByExample(@Param("record") FmRole record, @Param("example") FmRoleExample example);
}