package cn.cs.fileManager.dao.mapper;

import cn.cs.fileManager.dao.model.FmUser;
import cn.cs.fileManager.dao.model.FmUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FmUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_user
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	long countByExample(FmUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_user
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	int deleteByExample(FmUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_user
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	int insert(FmUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_user
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	int insertSelective(FmUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_user
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	List<FmUser> selectByExample(FmUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_user
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	int updateByExampleSelective(@Param("record") FmUser record, @Param("example") FmUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_user
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	int updateByExample(@Param("record") FmUser record, @Param("example") FmUserExample example);
}