package cn.cs.fileManager.dao.model;

public class FmFileType {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_file_type.id
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_file_type.type_name
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	private String typeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_file_type.file_ext
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	private String fileExt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_file_type.content_type
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	private String contentType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_file_type.max_upload_size
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	private Integer maxUploadSize;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_file_type.max_download_size
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	private Integer maxDownloadSize;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_file_type.valid
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	private String valid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_file_type.id
	 * @return  the value of fm_file_type.id
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_file_type.id
	 * @param id  the value for fm_file_type.id
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_file_type.type_name
	 * @return  the value of fm_file_type.type_name
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public String getTypeName() {
		return typeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_file_type.type_name
	 * @param typeName  the value for fm_file_type.type_name
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_file_type.file_ext
	 * @return  the value of fm_file_type.file_ext
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public String getFileExt() {
		return fileExt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_file_type.file_ext
	 * @param fileExt  the value for fm_file_type.file_ext
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public void setFileExt(String fileExt) {
		this.fileExt = fileExt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_file_type.content_type
	 * @return  the value of fm_file_type.content_type
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public String getContentType() {
		return contentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_file_type.content_type
	 * @param contentType  the value for fm_file_type.content_type
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_file_type.max_upload_size
	 * @return  the value of fm_file_type.max_upload_size
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public Integer getMaxUploadSize() {
		return maxUploadSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_file_type.max_upload_size
	 * @param maxUploadSize  the value for fm_file_type.max_upload_size
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public void setMaxUploadSize(Integer maxUploadSize) {
		this.maxUploadSize = maxUploadSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_file_type.max_download_size
	 * @return  the value of fm_file_type.max_download_size
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public Integer getMaxDownloadSize() {
		return maxDownloadSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_file_type.max_download_size
	 * @param maxDownloadSize  the value for fm_file_type.max_download_size
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public void setMaxDownloadSize(Integer maxDownloadSize) {
		this.maxDownloadSize = maxDownloadSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_file_type.valid
	 * @return  the value of fm_file_type.valid
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public String getValid() {
		return valid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_file_type.valid
	 * @param valid  the value for fm_file_type.valid
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public void setValid(String valid) {
		this.valid = valid;
	}
}