package cn.cs.fileManager.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FmFileExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table fm_file
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table fm_file
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table fm_file
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_file
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public FmFileExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_file
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_file
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_file
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_file
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_file
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_file
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_file
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_file
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_file
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_file
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table fm_file
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andFolderIdIsNull() {
			addCriterion("folder_id is null");
			return (Criteria) this;
		}

		public Criteria andFolderIdIsNotNull() {
			addCriterion("folder_id is not null");
			return (Criteria) this;
		}

		public Criteria andFolderIdEqualTo(Long value) {
			addCriterion("folder_id =", value, "folderId");
			return (Criteria) this;
		}

		public Criteria andFolderIdNotEqualTo(Long value) {
			addCriterion("folder_id <>", value, "folderId");
			return (Criteria) this;
		}

		public Criteria andFolderIdGreaterThan(Long value) {
			addCriterion("folder_id >", value, "folderId");
			return (Criteria) this;
		}

		public Criteria andFolderIdGreaterThanOrEqualTo(Long value) {
			addCriterion("folder_id >=", value, "folderId");
			return (Criteria) this;
		}

		public Criteria andFolderIdLessThan(Long value) {
			addCriterion("folder_id <", value, "folderId");
			return (Criteria) this;
		}

		public Criteria andFolderIdLessThanOrEqualTo(Long value) {
			addCriterion("folder_id <=", value, "folderId");
			return (Criteria) this;
		}

		public Criteria andFolderIdIn(List<Long> values) {
			addCriterion("folder_id in", values, "folderId");
			return (Criteria) this;
		}

		public Criteria andFolderIdNotIn(List<Long> values) {
			addCriterion("folder_id not in", values, "folderId");
			return (Criteria) this;
		}

		public Criteria andFolderIdBetween(Long value1, Long value2) {
			addCriterion("folder_id between", value1, value2, "folderId");
			return (Criteria) this;
		}

		public Criteria andFolderIdNotBetween(Long value1, Long value2) {
			addCriterion("folder_id not between", value1, value2, "folderId");
			return (Criteria) this;
		}

		public Criteria andFileTrueNameIsNull() {
			addCriterion("file_true_name is null");
			return (Criteria) this;
		}

		public Criteria andFileTrueNameIsNotNull() {
			addCriterion("file_true_name is not null");
			return (Criteria) this;
		}

		public Criteria andFileTrueNameEqualTo(String value) {
			addCriterion("file_true_name =", value, "fileTrueName");
			return (Criteria) this;
		}

		public Criteria andFileTrueNameNotEqualTo(String value) {
			addCriterion("file_true_name <>", value, "fileTrueName");
			return (Criteria) this;
		}

		public Criteria andFileTrueNameGreaterThan(String value) {
			addCriterion("file_true_name >", value, "fileTrueName");
			return (Criteria) this;
		}

		public Criteria andFileTrueNameGreaterThanOrEqualTo(String value) {
			addCriterion("file_true_name >=", value, "fileTrueName");
			return (Criteria) this;
		}

		public Criteria andFileTrueNameLessThan(String value) {
			addCriterion("file_true_name <", value, "fileTrueName");
			return (Criteria) this;
		}

		public Criteria andFileTrueNameLessThanOrEqualTo(String value) {
			addCriterion("file_true_name <=", value, "fileTrueName");
			return (Criteria) this;
		}

		public Criteria andFileTrueNameLike(String value) {
			addCriterion("file_true_name like", value, "fileTrueName");
			return (Criteria) this;
		}

		public Criteria andFileTrueNameNotLike(String value) {
			addCriterion("file_true_name not like", value, "fileTrueName");
			return (Criteria) this;
		}

		public Criteria andFileTrueNameIn(List<String> values) {
			addCriterion("file_true_name in", values, "fileTrueName");
			return (Criteria) this;
		}

		public Criteria andFileTrueNameNotIn(List<String> values) {
			addCriterion("file_true_name not in", values, "fileTrueName");
			return (Criteria) this;
		}

		public Criteria andFileTrueNameBetween(String value1, String value2) {
			addCriterion("file_true_name between", value1, value2, "fileTrueName");
			return (Criteria) this;
		}

		public Criteria andFileTrueNameNotBetween(String value1, String value2) {
			addCriterion("file_true_name not between", value1, value2, "fileTrueName");
			return (Criteria) this;
		}

		public Criteria andFileNameIsNull() {
			addCriterion("file_name is null");
			return (Criteria) this;
		}

		public Criteria andFileNameIsNotNull() {
			addCriterion("file_name is not null");
			return (Criteria) this;
		}

		public Criteria andFileNameEqualTo(String value) {
			addCriterion("file_name =", value, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameNotEqualTo(String value) {
			addCriterion("file_name <>", value, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameGreaterThan(String value) {
			addCriterion("file_name >", value, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameGreaterThanOrEqualTo(String value) {
			addCriterion("file_name >=", value, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameLessThan(String value) {
			addCriterion("file_name <", value, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameLessThanOrEqualTo(String value) {
			addCriterion("file_name <=", value, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameLike(String value) {
			addCriterion("file_name like", value, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameNotLike(String value) {
			addCriterion("file_name not like", value, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameIn(List<String> values) {
			addCriterion("file_name in", values, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameNotIn(List<String> values) {
			addCriterion("file_name not in", values, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameBetween(String value1, String value2) {
			addCriterion("file_name between", value1, value2, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameNotBetween(String value1, String value2) {
			addCriterion("file_name not between", value1, value2, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileSizeIsNull() {
			addCriterion("file_size is null");
			return (Criteria) this;
		}

		public Criteria andFileSizeIsNotNull() {
			addCriterion("file_size is not null");
			return (Criteria) this;
		}

		public Criteria andFileSizeEqualTo(Integer value) {
			addCriterion("file_size =", value, "fileSize");
			return (Criteria) this;
		}

		public Criteria andFileSizeNotEqualTo(Integer value) {
			addCriterion("file_size <>", value, "fileSize");
			return (Criteria) this;
		}

		public Criteria andFileSizeGreaterThan(Integer value) {
			addCriterion("file_size >", value, "fileSize");
			return (Criteria) this;
		}

		public Criteria andFileSizeGreaterThanOrEqualTo(Integer value) {
			addCriterion("file_size >=", value, "fileSize");
			return (Criteria) this;
		}

		public Criteria andFileSizeLessThan(Integer value) {
			addCriterion("file_size <", value, "fileSize");
			return (Criteria) this;
		}

		public Criteria andFileSizeLessThanOrEqualTo(Integer value) {
			addCriterion("file_size <=", value, "fileSize");
			return (Criteria) this;
		}

		public Criteria andFileSizeIn(List<Integer> values) {
			addCriterion("file_size in", values, "fileSize");
			return (Criteria) this;
		}

		public Criteria andFileSizeNotIn(List<Integer> values) {
			addCriterion("file_size not in", values, "fileSize");
			return (Criteria) this;
		}

		public Criteria andFileSizeBetween(Integer value1, Integer value2) {
			addCriterion("file_size between", value1, value2, "fileSize");
			return (Criteria) this;
		}

		public Criteria andFileSizeNotBetween(Integer value1, Integer value2) {
			addCriterion("file_size not between", value1, value2, "fileSize");
			return (Criteria) this;
		}

		public Criteria andFileTypeIdIsNull() {
			addCriterion("file_type_id is null");
			return (Criteria) this;
		}

		public Criteria andFileTypeIdIsNotNull() {
			addCriterion("file_type_id is not null");
			return (Criteria) this;
		}

		public Criteria andFileTypeIdEqualTo(Long value) {
			addCriterion("file_type_id =", value, "fileTypeId");
			return (Criteria) this;
		}

		public Criteria andFileTypeIdNotEqualTo(Long value) {
			addCriterion("file_type_id <>", value, "fileTypeId");
			return (Criteria) this;
		}

		public Criteria andFileTypeIdGreaterThan(Long value) {
			addCriterion("file_type_id >", value, "fileTypeId");
			return (Criteria) this;
		}

		public Criteria andFileTypeIdGreaterThanOrEqualTo(Long value) {
			addCriterion("file_type_id >=", value, "fileTypeId");
			return (Criteria) this;
		}

		public Criteria andFileTypeIdLessThan(Long value) {
			addCriterion("file_type_id <", value, "fileTypeId");
			return (Criteria) this;
		}

		public Criteria andFileTypeIdLessThanOrEqualTo(Long value) {
			addCriterion("file_type_id <=", value, "fileTypeId");
			return (Criteria) this;
		}

		public Criteria andFileTypeIdIn(List<Long> values) {
			addCriterion("file_type_id in", values, "fileTypeId");
			return (Criteria) this;
		}

		public Criteria andFileTypeIdNotIn(List<Long> values) {
			addCriterion("file_type_id not in", values, "fileTypeId");
			return (Criteria) this;
		}

		public Criteria andFileTypeIdBetween(Long value1, Long value2) {
			addCriterion("file_type_id between", value1, value2, "fileTypeId");
			return (Criteria) this;
		}

		public Criteria andFileTypeIdNotBetween(Long value1, Long value2) {
			addCriterion("file_type_id not between", value1, value2, "fileTypeId");
			return (Criteria) this;
		}

		public Criteria andVerIsNull() {
			addCriterion("ver is null");
			return (Criteria) this;
		}

		public Criteria andVerIsNotNull() {
			addCriterion("ver is not null");
			return (Criteria) this;
		}

		public Criteria andVerEqualTo(Integer value) {
			addCriterion("ver =", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerNotEqualTo(Integer value) {
			addCriterion("ver <>", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerGreaterThan(Integer value) {
			addCriterion("ver >", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerGreaterThanOrEqualTo(Integer value) {
			addCriterion("ver >=", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerLessThan(Integer value) {
			addCriterion("ver <", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerLessThanOrEqualTo(Integer value) {
			addCriterion("ver <=", value, "ver");
			return (Criteria) this;
		}

		public Criteria andVerIn(List<Integer> values) {
			addCriterion("ver in", values, "ver");
			return (Criteria) this;
		}

		public Criteria andVerNotIn(List<Integer> values) {
			addCriterion("ver not in", values, "ver");
			return (Criteria) this;
		}

		public Criteria andVerBetween(Integer value1, Integer value2) {
			addCriterion("ver between", value1, value2, "ver");
			return (Criteria) this;
		}

		public Criteria andVerNotBetween(Integer value1, Integer value2) {
			addCriterion("ver not between", value1, value2, "ver");
			return (Criteria) this;
		}

		public Criteria andRegDateIsNull() {
			addCriterion("reg_date is null");
			return (Criteria) this;
		}

		public Criteria andRegDateIsNotNull() {
			addCriterion("reg_date is not null");
			return (Criteria) this;
		}

		public Criteria andRegDateEqualTo(Date value) {
			addCriterion("reg_date =", value, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateNotEqualTo(Date value) {
			addCriterion("reg_date <>", value, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateGreaterThan(Date value) {
			addCriterion("reg_date >", value, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateGreaterThanOrEqualTo(Date value) {
			addCriterion("reg_date >=", value, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateLessThan(Date value) {
			addCriterion("reg_date <", value, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateLessThanOrEqualTo(Date value) {
			addCriterion("reg_date <=", value, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateIn(List<Date> values) {
			addCriterion("reg_date in", values, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateNotIn(List<Date> values) {
			addCriterion("reg_date not in", values, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateBetween(Date value1, Date value2) {
			addCriterion("reg_date between", value1, value2, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateNotBetween(Date value1, Date value2) {
			addCriterion("reg_date not between", value1, value2, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegAccountIsNull() {
			addCriterion("reg_account is null");
			return (Criteria) this;
		}

		public Criteria andRegAccountIsNotNull() {
			addCriterion("reg_account is not null");
			return (Criteria) this;
		}

		public Criteria andRegAccountEqualTo(String value) {
			addCriterion("reg_account =", value, "regAccount");
			return (Criteria) this;
		}

		public Criteria andRegAccountNotEqualTo(String value) {
			addCriterion("reg_account <>", value, "regAccount");
			return (Criteria) this;
		}

		public Criteria andRegAccountGreaterThan(String value) {
			addCriterion("reg_account >", value, "regAccount");
			return (Criteria) this;
		}

		public Criteria andRegAccountGreaterThanOrEqualTo(String value) {
			addCriterion("reg_account >=", value, "regAccount");
			return (Criteria) this;
		}

		public Criteria andRegAccountLessThan(String value) {
			addCriterion("reg_account <", value, "regAccount");
			return (Criteria) this;
		}

		public Criteria andRegAccountLessThanOrEqualTo(String value) {
			addCriterion("reg_account <=", value, "regAccount");
			return (Criteria) this;
		}

		public Criteria andRegAccountLike(String value) {
			addCriterion("reg_account like", value, "regAccount");
			return (Criteria) this;
		}

		public Criteria andRegAccountNotLike(String value) {
			addCriterion("reg_account not like", value, "regAccount");
			return (Criteria) this;
		}

		public Criteria andRegAccountIn(List<String> values) {
			addCriterion("reg_account in", values, "regAccount");
			return (Criteria) this;
		}

		public Criteria andRegAccountNotIn(List<String> values) {
			addCriterion("reg_account not in", values, "regAccount");
			return (Criteria) this;
		}

		public Criteria andRegAccountBetween(String value1, String value2) {
			addCriterion("reg_account between", value1, value2, "regAccount");
			return (Criteria) this;
		}

		public Criteria andRegAccountNotBetween(String value1, String value2) {
			addCriterion("reg_account not between", value1, value2, "regAccount");
			return (Criteria) this;
		}

		public Criteria andUpdDateIsNull() {
			addCriterion("upd_date is null");
			return (Criteria) this;
		}

		public Criteria andUpdDateIsNotNull() {
			addCriterion("upd_date is not null");
			return (Criteria) this;
		}

		public Criteria andUpdDateEqualTo(Date value) {
			addCriterion("upd_date =", value, "updDate");
			return (Criteria) this;
		}

		public Criteria andUpdDateNotEqualTo(Date value) {
			addCriterion("upd_date <>", value, "updDate");
			return (Criteria) this;
		}

		public Criteria andUpdDateGreaterThan(Date value) {
			addCriterion("upd_date >", value, "updDate");
			return (Criteria) this;
		}

		public Criteria andUpdDateGreaterThanOrEqualTo(Date value) {
			addCriterion("upd_date >=", value, "updDate");
			return (Criteria) this;
		}

		public Criteria andUpdDateLessThan(Date value) {
			addCriterion("upd_date <", value, "updDate");
			return (Criteria) this;
		}

		public Criteria andUpdDateLessThanOrEqualTo(Date value) {
			addCriterion("upd_date <=", value, "updDate");
			return (Criteria) this;
		}

		public Criteria andUpdDateIn(List<Date> values) {
			addCriterion("upd_date in", values, "updDate");
			return (Criteria) this;
		}

		public Criteria andUpdDateNotIn(List<Date> values) {
			addCriterion("upd_date not in", values, "updDate");
			return (Criteria) this;
		}

		public Criteria andUpdDateBetween(Date value1, Date value2) {
			addCriterion("upd_date between", value1, value2, "updDate");
			return (Criteria) this;
		}

		public Criteria andUpdDateNotBetween(Date value1, Date value2) {
			addCriterion("upd_date not between", value1, value2, "updDate");
			return (Criteria) this;
		}

		public Criteria andUpdAccountIsNull() {
			addCriterion("upd_account is null");
			return (Criteria) this;
		}

		public Criteria andUpdAccountIsNotNull() {
			addCriterion("upd_account is not null");
			return (Criteria) this;
		}

		public Criteria andUpdAccountEqualTo(String value) {
			addCriterion("upd_account =", value, "updAccount");
			return (Criteria) this;
		}

		public Criteria andUpdAccountNotEqualTo(String value) {
			addCriterion("upd_account <>", value, "updAccount");
			return (Criteria) this;
		}

		public Criteria andUpdAccountGreaterThan(String value) {
			addCriterion("upd_account >", value, "updAccount");
			return (Criteria) this;
		}

		public Criteria andUpdAccountGreaterThanOrEqualTo(String value) {
			addCriterion("upd_account >=", value, "updAccount");
			return (Criteria) this;
		}

		public Criteria andUpdAccountLessThan(String value) {
			addCriterion("upd_account <", value, "updAccount");
			return (Criteria) this;
		}

		public Criteria andUpdAccountLessThanOrEqualTo(String value) {
			addCriterion("upd_account <=", value, "updAccount");
			return (Criteria) this;
		}

		public Criteria andUpdAccountLike(String value) {
			addCriterion("upd_account like", value, "updAccount");
			return (Criteria) this;
		}

		public Criteria andUpdAccountNotLike(String value) {
			addCriterion("upd_account not like", value, "updAccount");
			return (Criteria) this;
		}

		public Criteria andUpdAccountIn(List<String> values) {
			addCriterion("upd_account in", values, "updAccount");
			return (Criteria) this;
		}

		public Criteria andUpdAccountNotIn(List<String> values) {
			addCriterion("upd_account not in", values, "updAccount");
			return (Criteria) this;
		}

		public Criteria andUpdAccountBetween(String value1, String value2) {
			addCriterion("upd_account between", value1, value2, "updAccount");
			return (Criteria) this;
		}

		public Criteria andUpdAccountNotBetween(String value1, String value2) {
			addCriterion("upd_account not between", value1, value2, "updAccount");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNull() {
			addCriterion("description is null");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNotNull() {
			addCriterion("description is not null");
			return (Criteria) this;
		}

		public Criteria andDescriptionEqualTo(String value) {
			addCriterion("description =", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotEqualTo(String value) {
			addCriterion("description <>", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThan(String value) {
			addCriterion("description >", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("description >=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThan(String value) {
			addCriterion("description <", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThanOrEqualTo(String value) {
			addCriterion("description <=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLike(String value) {
			addCriterion("description like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotLike(String value) {
			addCriterion("description not like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionIn(List<String> values) {
			addCriterion("description in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotIn(List<String> values) {
			addCriterion("description not in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionBetween(String value1, String value2) {
			addCriterion("description between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotBetween(String value1, String value2) {
			addCriterion("description not between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andValidIsNull() {
			addCriterion("valid is null");
			return (Criteria) this;
		}

		public Criteria andValidIsNotNull() {
			addCriterion("valid is not null");
			return (Criteria) this;
		}

		public Criteria andValidEqualTo(String value) {
			addCriterion("valid =", value, "valid");
			return (Criteria) this;
		}

		public Criteria andValidNotEqualTo(String value) {
			addCriterion("valid <>", value, "valid");
			return (Criteria) this;
		}

		public Criteria andValidGreaterThan(String value) {
			addCriterion("valid >", value, "valid");
			return (Criteria) this;
		}

		public Criteria andValidGreaterThanOrEqualTo(String value) {
			addCriterion("valid >=", value, "valid");
			return (Criteria) this;
		}

		public Criteria andValidLessThan(String value) {
			addCriterion("valid <", value, "valid");
			return (Criteria) this;
		}

		public Criteria andValidLessThanOrEqualTo(String value) {
			addCriterion("valid <=", value, "valid");
			return (Criteria) this;
		}

		public Criteria andValidLike(String value) {
			addCriterion("valid like", value, "valid");
			return (Criteria) this;
		}

		public Criteria andValidNotLike(String value) {
			addCriterion("valid not like", value, "valid");
			return (Criteria) this;
		}

		public Criteria andValidIn(List<String> values) {
			addCriterion("valid in", values, "valid");
			return (Criteria) this;
		}

		public Criteria andValidNotIn(List<String> values) {
			addCriterion("valid not in", values, "valid");
			return (Criteria) this;
		}

		public Criteria andValidBetween(String value1, String value2) {
			addCriterion("valid between", value1, value2, "valid");
			return (Criteria) this;
		}

		public Criteria andValidNotBetween(String value1, String value2) {
			addCriterion("valid not between", value1, value2, "valid");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table fm_file
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fm_file
     *
     * @mbg.generated do_not_delete_during_merge Sun Dec 02 21:55:10 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}