package cn.cs.fileManager.dao.model;

import java.util.Date;

public class FmFile {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_file.id
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_file.folder_id
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	private Long folderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_file.file_true_name
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	private String fileTrueName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_file.file_name
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	private String fileName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_file.file_size
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	private Integer fileSize;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_file.file_type_id
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	private Long fileTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_file.ver
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	private Integer ver;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_file.reg_date
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	private Date regDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_file.reg_account
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	private Long regAccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_file.upd_date
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	private Date updDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_file.upd_account
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	private Long updAccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_file.description
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_file.valid
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	private String valid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_file.id
	 * @return  the value of fm_file.id
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_file.id
	 * @param id  the value for fm_file.id
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_file.folder_id
	 * @return  the value of fm_file.folder_id
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public Long getFolderId() {
		return folderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_file.folder_id
	 * @param folderId  the value for fm_file.folder_id
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public void setFolderId(Long folderId) {
		this.folderId = folderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_file.file_true_name
	 * @return  the value of fm_file.file_true_name
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public String getFileTrueName() {
		return fileTrueName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_file.file_true_name
	 * @param fileTrueName  the value for fm_file.file_true_name
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public void setFileTrueName(String fileTrueName) {
		this.fileTrueName = fileTrueName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_file.file_name
	 * @return  the value of fm_file.file_name
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public String getFileName() {
		return fileName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_file.file_name
	 * @param fileName  the value for fm_file.file_name
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_file.file_size
	 * @return  the value of fm_file.file_size
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public Integer getFileSize() {
		return fileSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_file.file_size
	 * @param fileSize  the value for fm_file.file_size
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public void setFileSize(Integer fileSize) {
		this.fileSize = fileSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_file.file_type_id
	 * @return  the value of fm_file.file_type_id
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public Long getFileTypeId() {
		return fileTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_file.file_type_id
	 * @param fileTypeId  the value for fm_file.file_type_id
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public void setFileTypeId(Long fileTypeId) {
		this.fileTypeId = fileTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_file.ver
	 * @return  the value of fm_file.ver
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public Integer getVer() {
		return ver;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_file.ver
	 * @param ver  the value for fm_file.ver
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public void setVer(Integer ver) {
		this.ver = ver;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_file.reg_date
	 * @return  the value of fm_file.reg_date
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public Date getRegDate() {
		return regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_file.reg_date
	 * @param regDate  the value for fm_file.reg_date
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_file.reg_account
	 * @return  the value of fm_file.reg_account
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public Long getRegAccount() {
		return regAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_file.reg_account
	 * @param regAccount  the value for fm_file.reg_account
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public void setRegAccount(Long regAccount) {
		this.regAccount = regAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_file.upd_date
	 * @return  the value of fm_file.upd_date
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public Date getUpdDate() {
		return updDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_file.upd_date
	 * @param updDate  the value for fm_file.upd_date
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public void setUpdDate(Date updDate) {
		this.updDate = updDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_file.upd_account
	 * @return  the value of fm_file.upd_account
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public Long getUpdAccount() {
		return updAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_file.upd_account
	 * @param updAccount  the value for fm_file.upd_account
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public void setUpdAccount(Long updAccount) {
		this.updAccount = updAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_file.description
	 * @return  the value of fm_file.description
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_file.description
	 * @param description  the value for fm_file.description
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_file.valid
	 * @return  the value of fm_file.valid
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public String getValid() {
		return valid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_file.valid
	 * @param valid  the value for fm_file.valid
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public void setValid(String valid) {
		this.valid = valid;
	}
}