package cn.cs.fileManager.dao.model;

import java.util.Date;

public class FmFolder {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_folder.id
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_folder.folder_name
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	private String folderName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_folder.p_id
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	private Long pId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_folder.owner
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	private String owner;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_folder.base_dir
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	private String baseDir;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_folder.reg_date
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	private Date regDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_folder.reg_account
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	private String regAccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_folder.description
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_folder.valid
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	private String valid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_folder.id
	 * @return  the value of fm_folder.id
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_folder.id
	 * @param id  the value for fm_folder.id
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_folder.folder_name
	 * @return  the value of fm_folder.folder_name
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public String getFolderName() {
		return folderName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_folder.folder_name
	 * @param folderName  the value for fm_folder.folder_name
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public void setFolderName(String folderName) {
		this.folderName = folderName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_folder.p_id
	 * @return  the value of fm_folder.p_id
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public Long getpId() {
		return pId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_folder.p_id
	 * @param pId  the value for fm_folder.p_id
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public void setpId(Long pId) {
		this.pId = pId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_folder.owner
	 * @return  the value of fm_folder.owner
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public String getOwner() {
		return owner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_folder.owner
	 * @param owner  the value for fm_folder.owner
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public void setOwner(String owner) {
		this.owner = owner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_folder.base_dir
	 * @return  the value of fm_folder.base_dir
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public String getBaseDir() {
		return baseDir;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_folder.base_dir
	 * @param baseDir  the value for fm_folder.base_dir
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public void setBaseDir(String baseDir) {
		this.baseDir = baseDir;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_folder.reg_date
	 * @return  the value of fm_folder.reg_date
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public Date getRegDate() {
		return regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_folder.reg_date
	 * @param regDate  the value for fm_folder.reg_date
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_folder.reg_account
	 * @return  the value of fm_folder.reg_account
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public String getRegAccount() {
		return regAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_folder.reg_account
	 * @param regAccount  the value for fm_folder.reg_account
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public void setRegAccount(String regAccount) {
		this.regAccount = regAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_folder.description
	 * @return  the value of fm_folder.description
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_folder.description
	 * @param description  the value for fm_folder.description
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_folder.valid
	 * @return  the value of fm_folder.valid
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public String getValid() {
		return valid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_folder.valid
	 * @param valid  the value for fm_folder.valid
	 * @mbg.generated  Thu Dec 20 16:13:57 CST 2018
	 */
	public void setValid(String valid) {
		this.valid = valid;
	}
}