package cn.cs.fileManager.dao.model;

public class FmRole {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_role.role_id
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	private Long roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_role.role_name
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	private String roleName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_role.role_status
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	private String roleStatus;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_role.role_id
	 * @return  the value of fm_role.role_id
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	public Long getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_role.role_id
	 * @param roleId  the value for fm_role.role_id
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_role.role_name
	 * @return  the value of fm_role.role_name
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	public String getRoleName() {
		return roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_role.role_name
	 * @param roleName  the value for fm_role.role_name
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_role.role_status
	 * @return  the value of fm_role.role_status
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	public String getRoleStatus() {
		return roleStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_role.role_status
	 * @param roleStatus  the value for fm_role.role_status
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	public void setRoleStatus(String roleStatus) {
		this.roleStatus = roleStatus;
	}
}