package cn.cs.fileManager.dao.model;


import java.util.Date;
import java.util.List;

import lombok.Data;

@Data
public class FmUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_user.id
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_user.login_name
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	private String loginName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_user.password
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_user.mobile_number
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	private String mobileNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_user.last_login_date
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	private Date lastLoginDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_user.valid
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	private String valid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_user.name
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_user.id
	 * @return  the value of fm_user.id
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	/**
     * 角色信息
     */
    private List<String> roles;
    
    
	
}