package cn.cs.fileManager.dao.model;

import java.util.Date;

public class FmUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_user.id
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_user.login_name
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	private String loginName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_user.password
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_user.mobile_number
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	private String mobileNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_user.last_login_date
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	private Date lastLoginDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_user.type
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_user.valid
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	private String valid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_user.id
	 * @return  the value of fm_user.id
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_user.id
	 * @param id  the value for fm_user.id
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_user.login_name
	 * @return  the value of fm_user.login_name
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public String getLoginName() {
		return loginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_user.login_name
	 * @param loginName  the value for fm_user.login_name
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_user.password
	 * @return  the value of fm_user.password
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_user.password
	 * @param password  the value for fm_user.password
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_user.mobile_number
	 * @return  the value of fm_user.mobile_number
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public String getMobileNumber() {
		return mobileNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_user.mobile_number
	 * @param mobileNumber  the value for fm_user.mobile_number
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_user.last_login_date
	 * @return  the value of fm_user.last_login_date
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public Date getLastLoginDate() {
		return lastLoginDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_user.last_login_date
	 * @param lastLoginDate  the value for fm_user.last_login_date
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public void setLastLoginDate(Date lastLoginDate) {
		this.lastLoginDate = lastLoginDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_user.type
	 * @return  the value of fm_user.type
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_user.type
	 * @param type  the value for fm_user.type
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_user.valid
	 * @return  the value of fm_user.valid
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public String getValid() {
		return valid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_user.valid
	 * @param valid  the value for fm_user.valid
	 * @mbg.generated  Thu May 23 19:13:30 CST 2019
	 */
	public void setValid(String valid) {
		this.valid = valid;
	}
}