package cn.cs.fileManager.dao.model;

import java.util.ArrayList;
import java.util.List;

public class FmUserRoleExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table fm_user_role
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table fm_user_role
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table fm_user_role
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_user_role
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	public FmUserRoleExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_user_role
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_user_role
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_user_role
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_user_role
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_user_role
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_user_role
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_user_role
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_user_role
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_user_role
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_user_role
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table fm_user_role
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andUserRoleIdIsNull() {
			addCriterion("user_role_id is null");
			return (Criteria) this;
		}

		public Criteria andUserRoleIdIsNotNull() {
			addCriterion("user_role_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserRoleIdEqualTo(Long value) {
			addCriterion("user_role_id =", value, "userRoleId");
			return (Criteria) this;
		}

		public Criteria andUserRoleIdNotEqualTo(Long value) {
			addCriterion("user_role_id <>", value, "userRoleId");
			return (Criteria) this;
		}

		public Criteria andUserRoleIdGreaterThan(Long value) {
			addCriterion("user_role_id >", value, "userRoleId");
			return (Criteria) this;
		}

		public Criteria andUserRoleIdGreaterThanOrEqualTo(Long value) {
			addCriterion("user_role_id >=", value, "userRoleId");
			return (Criteria) this;
		}

		public Criteria andUserRoleIdLessThan(Long value) {
			addCriterion("user_role_id <", value, "userRoleId");
			return (Criteria) this;
		}

		public Criteria andUserRoleIdLessThanOrEqualTo(Long value) {
			addCriterion("user_role_id <=", value, "userRoleId");
			return (Criteria) this;
		}

		public Criteria andUserRoleIdIn(List<Long> values) {
			addCriterion("user_role_id in", values, "userRoleId");
			return (Criteria) this;
		}

		public Criteria andUserRoleIdNotIn(List<Long> values) {
			addCriterion("user_role_id not in", values, "userRoleId");
			return (Criteria) this;
		}

		public Criteria andUserRoleIdBetween(Long value1, Long value2) {
			addCriterion("user_role_id between", value1, value2, "userRoleId");
			return (Criteria) this;
		}

		public Criteria andUserRoleIdNotBetween(Long value1, Long value2) {
			addCriterion("user_role_id not between", value1, value2, "userRoleId");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Long value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Long value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Long value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Long value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Long value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Long> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Long> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Long value1, Long value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Long value1, Long value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andRoleIdIsNull() {
			addCriterion("role_id is null");
			return (Criteria) this;
		}

		public Criteria andRoleIdIsNotNull() {
			addCriterion("role_id is not null");
			return (Criteria) this;
		}

		public Criteria andRoleIdEqualTo(Long value) {
			addCriterion("role_id =", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdNotEqualTo(Long value) {
			addCriterion("role_id <>", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdGreaterThan(Long value) {
			addCriterion("role_id >", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdGreaterThanOrEqualTo(Long value) {
			addCriterion("role_id >=", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdLessThan(Long value) {
			addCriterion("role_id <", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdLessThanOrEqualTo(Long value) {
			addCriterion("role_id <=", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdIn(List<Long> values) {
			addCriterion("role_id in", values, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdNotIn(List<Long> values) {
			addCriterion("role_id not in", values, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdBetween(Long value1, Long value2) {
			addCriterion("role_id between", value1, value2, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdNotBetween(Long value1, Long value2) {
			addCriterion("role_id not between", value1, value2, "roleId");
			return (Criteria) this;
		}

		public Criteria andUserRoleStatusIsNull() {
			addCriterion("user_role_status is null");
			return (Criteria) this;
		}

		public Criteria andUserRoleStatusIsNotNull() {
			addCriterion("user_role_status is not null");
			return (Criteria) this;
		}

		public Criteria andUserRoleStatusEqualTo(String value) {
			addCriterion("user_role_status =", value, "userRoleStatus");
			return (Criteria) this;
		}

		public Criteria andUserRoleStatusNotEqualTo(String value) {
			addCriterion("user_role_status <>", value, "userRoleStatus");
			return (Criteria) this;
		}

		public Criteria andUserRoleStatusGreaterThan(String value) {
			addCriterion("user_role_status >", value, "userRoleStatus");
			return (Criteria) this;
		}

		public Criteria andUserRoleStatusGreaterThanOrEqualTo(String value) {
			addCriterion("user_role_status >=", value, "userRoleStatus");
			return (Criteria) this;
		}

		public Criteria andUserRoleStatusLessThan(String value) {
			addCriterion("user_role_status <", value, "userRoleStatus");
			return (Criteria) this;
		}

		public Criteria andUserRoleStatusLessThanOrEqualTo(String value) {
			addCriterion("user_role_status <=", value, "userRoleStatus");
			return (Criteria) this;
		}

		public Criteria andUserRoleStatusLike(String value) {
			addCriterion("user_role_status like", value, "userRoleStatus");
			return (Criteria) this;
		}

		public Criteria andUserRoleStatusNotLike(String value) {
			addCriterion("user_role_status not like", value, "userRoleStatus");
			return (Criteria) this;
		}

		public Criteria andUserRoleStatusIn(List<String> values) {
			addCriterion("user_role_status in", values, "userRoleStatus");
			return (Criteria) this;
		}

		public Criteria andUserRoleStatusNotIn(List<String> values) {
			addCriterion("user_role_status not in", values, "userRoleStatus");
			return (Criteria) this;
		}

		public Criteria andUserRoleStatusBetween(String value1, String value2) {
			addCriterion("user_role_status between", value1, value2, "userRoleStatus");
			return (Criteria) this;
		}

		public Criteria andUserRoleStatusNotBetween(String value1, String value2) {
			addCriterion("user_role_status not between", value1, value2, "userRoleStatus");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table fm_user_role
	 * @mbg.generated  Fri May 24 14:57:35 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fm_user_role
     *
     * @mbg.generated do_not_delete_during_merge Fri May 24 14:37:12 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}